#+TITLE: Chu's Literate DOOM GNU Emacs Package Configuration
#+AUTHOR: Chu the Pup
#+DESCRIPTION: Chu's favorite packages to fondle.
#+PROPERTY: header-args :tangle yes
#+AUTO-TANGLE: t
* Package Config
** DOOM packages.el preamble
#+begin_src emacs-lisp
;; -*- no-byte-compile: t; -*-
#+end_src
#+begin_example emacs-lisp
;;; $DOOMDIR/packages.el

;; see package.org instead of this file

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or
;; use 'M-x doom/reload'.

;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/raxod502/straight.el#the-recipe-format
(package! another-package
  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
(package! this-package
  :recipe (:host github :repo "username/repo"
           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
(package! builtin-package :recipe (:nonrecursive t))
(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see raxod502/straight.el#279)
(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
(package! builtin-package :pin "1a2b3c4d5e")
;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
(unpin! pinned-package)
;; ...or multiple packages
(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
(unpin! t)
#+end_example
** Chu's fixes and patches
Not actually mine, just collected by me, for me.
#+begin_src emacs-lisp
;(package! transient :pin "c2bdf7e12c530eb85476d3aef317eb2941ab9440")
;(package! with-editor :pin "391e76a256aeec6b9e4cbd733088f30c677d965b")
#+end_src
** Chu's package(s)
*** common lisp yasnippets snippets
#+begin_src elisp
(package! common-lisp-snippets)
#+end_src
*** Add a random splash image to be shown on Emacs startup.
check in config.org for settings
#+begin_src elisp
(package! random-splash-image)
#+end_src
*** Org mode packages
**** org-auto-tangle
#+begin_src elisp
(package! org-auto-tangle)
#+end_src
**** org-drill
#+begin_src elisp
(package! org-drill)
#+end_src
**** org-bullets
Not necessary when using (org ... +pretty ...) mode w/ Doom Emacs. Expensive (processing-power-wise) to run, so disabled by default.
#+begin_example elisp
(package! org-bullets)
#+end_example
**** org-download
lets you copy and paste to and from emacs (images I mean)
#+begin_src elisp
(package! org-download
  :recipe (:host github
           :repo "abo-abo/org-download"
           :files ("org-download.el")))
#+end_src
**** org-pandoc-import
Leverage Pandoc to convert selected file types to org.
#+begin_src elisp
(package! org-pandoc-import
  :recipe (:host github
           :repo "tecosaur/org-pandoc-import"
           :files ("*.el" "filters" "preprocessors")))
#+end_src
**** org-roam
***** org-roam-ui
#+begin_src elisp
(package! org-roam-ui)
#+end_src
**** literate programming packages
***** literate-lisp
#+begin_src elisp
(package! literate-lisp
  :recipe (:host github :repo "jingtaozf/literate-lisp"))
#+end_src
**** citeproc
#+begin_example elisp
(package! citeproc)
#+end_example
*** Geiser
Geiser is used to interact with Scheme Lisp languages more easily.

Enable schemes in ~/.doom.d/init.el

(No need to enable w/ doom emacs)

#+begin_src elisp
;;(package! geiser)
#+end_src
**** Geiser macro stepper
Allows for macro stepping in Geiser.
#+begin_src elisp
;;(package! macrostep-geiser)
#+end_src
*** Add Structure and Interpretations of Computer Programs to the info menu
It's a book
#+begin_src elisp
(package! sicp)
#+end_src
*** common lisp hyperspec
#+begin_src elisp
(package! clhs)
#+end_src
*** paredit
#+begin_src elisp
(package! paredit)
#+end_src
*** command log mode
#+begin_src elisp
(package! command-log-mode)
#+end_src
*** Discord active presence
basically shows off what you're doing in Emacs to folks on Discord, what version/type of Emacs you're running (e.g. Doom, Spacemacs, or whatever).
#+begin_src elisp
(package! elcord)
#+end_src
*** Unofficial Telegram client
#+begin_src elisp :tangle no
(package! telega)
#+end_src
*** Nov.el
nov.el provides a major mode for reading EPUB documents (pdfs still work better).
#+begin_src elisp
(package! nov)
#+end_src
*** Rainbow-blocks
#+begin_src elisp
(package! rainbow-blocks)
#+end_src
*** achievements
#+begin_src elisp
(package! achievements)
#+end_src
*** csv-mode for csv file support
#+begin_src elisp
(package! csv-mode)
#+end_src
*** skeletor - project skeletons
#+begin_src elisp
(package! skeletor)
#+end_src
*** simple-httpd
#+begin_src elisp
(package! simple-httpd)
#+end_src
*** dwarf fortress raw file major mode
#+begin_src elisp
(package! dfraw-mode
  :recipe (:host github :repo "pthariensflame/dfraw-mode"))
#+end_src
*** Lorem Ipsum for Emacs
Add filler text to Emacs
#+begin_src elisp
(package! lorem-ipsum)
#+end_src
*** fragtog latex previews
#+begin_src elisp
(package! org-fragtog)
#+end_src
*** ledger import
#+begin_src elisp
(package! ledger-import)
#+end_src
*** Literate Emacs Calc Calculator Mode
#+begin_src elisp
(package! literate-calc-mode)
#+end_src
*** Alarm clock (for cooking)
#+begin_src elisp
(package! alarm-clock)
#+end_src
*** Async Fuzzy Finder for Emacs
#+begin_src elisp
(package! affe)
#+end_src
*** find-dired+.el
#+begin_src elisp
(package! find-dired+)
#+end_src
