#!/bin/sh
# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias $command="sudo $command"
done
unset command

se() {
	cd ~/.local/bin
	$EDITOR $(fzf)
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	lsblk="lsblk --output NAME,LABEL,TRAN,TYPE,SIZE,FSUSED,FSTYPE,MOUNTPOINT"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source \${XDG_CONFIG_HOME:-\$HOME/.config}/shell/shortcutrc ; source \${XDG_CONFIG_HOME:-\$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S \${XDG_CACHE_HOME:-\$HOME/.cache}/weatherreport"

alias \
	ezo="emacsclient -c" \
	exz="exec zsh" \
	vm="virt-manager && exit" \
	dooms="doom sync" \
	doomsp="doom sync -p" \
	doomb="doom build" \
	doomc="doom clean" \
	doomp="doom purge" \
	doomu="doom upgrade" \
	rosr="rlwrap ros dynamic-space-size=8000 run" \
	neofetch="hyfetch" \
	musescore="mscore" \
	ms="mscore" \
	lgc="looking-glass-client" \
	screm="scream -i virbr0" \
	chumacs="emacs --profile chumacs" \
	parrot="curl parrot.live" \
	ncduu="ncdu --exclude-kernfs --exclude /mnt --exclude /run/media --exclude /tmp" \
	dolphin="dolphin --platformtheme qt6ct" \
	kdenlive="kdenlive --platformtheme qt6ct" \
	otdk="otd loadsettings \${XDG_CONFIG_HOME:-\$HOME/.config}/OpenTabletDriver/Settings/huion-kamvas-13.json ; otd applypreset huion-kamvas-13" \
	gldl="gallery-dl --cookies-from-browser firefox "
