#!/bin/sh
# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
xrandr --dpi 96 && # Set DPI. User may want to use a larger number for larger screens.
# screenlayout &&    # set custom screen layout. set your own w/ `arandr`, save to ~/.local/bin/chus/screenlayout & replace
setbg &            # set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps &           # run the remaps script, switching caps/esc and more; check it for more info
emacs --daemon &   # start emacs daemon like this because systemd fucks up emacsclient
redshift &         # screen brightness tone warmer that tracks time of day
a2ln &             # android notifications (requires pairing first)
xdotool mousemove 960 540 & # move mouse to preferred monitor before starting gui programs

autostart="mpd picom unclutter dunst pipewire"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
