#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# screenlayout &&    # set custom screen layout. set your own w/ `arandr`, save to ~/.local/bin/chus/screenlayout & replace
xrandr --dpi 96 #&& # Set DPI. User may want to use a larger number for larger screens.
setbg &            # set the background with the `setbg` script
# xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
# remaps &           # run the remaps script, switching caps/esc and more; check it for more info
# emacs --daemon &   # start emacs daemon like this because systemd fucks up emacsclient
# redshift &         # screen dimming / tone warmer that tracks time of day
# a2ln &             # android 2 linux notification daemon (requires pre-pairing process for your phone)
# xdotool mousemove 960 540 & # move mouse to preferred monitor before starting gui programs

# autostart="mpd picom unclutter dunst pipewire rs keepassxc redshift"
autostart="mpd xcompmgr dunst unclutter pipewire remapd"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# mover & # move my applications to specified workspaces after programs get autostarted

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
